services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    
  db-migration:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.migration
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
      
  frontend:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.frontend
      args:
        - HTTP_URL=http://localhost:3001
        - WS_URL=ws://localhost:8080
    extra_hosts:
      - "localhost:host-gateway"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - http-backend
      - websocket-backend

  http-backend:
    build: 
      context: .
      dockerfile: ./Docker/Dockerfile.http-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEN_AI_API_KEY=${GEN_AI_API_KEY}
    ports:
      - 3001:3001
    depends_on: 
      - postgres

  websocket-backend:
    build: 
      context: .
      dockerfile: ./Docker/Dockerfile.websocket-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8080:8080
    depends_on:
      - postgres