FROM node:22-alpine

WORKDIR /src

RUN npm i -g pnpm

COPY ./packages ./packages
COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./turbo.json ./
COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install

ENV PORT=3001

RUN pnpm run build:http

EXPOSE 3001

CMD [ "pnpm", "run", "start:http" ]