FROM node:22-alpine

WORKDIR /src

RUN npm i -g pnpm

COPY ./packages ./packages
COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./turbo.json ./
COPY ./apps/websocket-backend ./apps/websocket-backend

RUN pnpm install

RUN pnpm run build:ws

EXPOSE 8080

CMD [ "pnpm", "run", "start:ws" ]