FROM node:22-alpine

WORKDIR /app

RUN npm i -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY ./packages ./packages

RUN pnpm install

CMD ["pnpm", "run", "db:migrate"]