FROM node:22-alpine

WORKDIR /src

RUN npm i -g pnpm

COPY ./packages ./packages
COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./turbo.json ./
COPY ./apps/frontend/package.json ./apps/frontend/package.json

RUN pnpm install

COPY ./apps/frontend ./apps/frontend

RUN pnpm run build:frontend

EXPOSE 3000

CMD ["pnpm", "run", "start:frontend"]