FROM node:22-alpine

WORKDIR /src

RUN npm i -g pnpm

COPY ./packages ./packages
COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./turbo.json ./
COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install

RUN pnpm run build:http

ENV PORT=3001
ENV GOOGLE_GENERATIVE_AI_API_KEY=${GEN_AI_API_KEY}

EXPOSE 3001

CMD [ "pnpm", "run", "start:http" ]