name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/Dockerfile.frontend
          push: true
          tags: |
            devanshbhavsar/drawify-frontend:latest
            devanshbhavsar/drawify-frontend:${{ github.sha }}

      - name: running docker container on vm
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker image prune -f
            docker pull devanshbhavsar/drawify-frontend:latest
            docker run -d -p 3000:3000 --name frontend-app -e DATABASE_URL=${{secrets.DATABASE_URL}} devanshbhavsar/drawify-frontend:latest
