name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/Dockerfile.frontend
          build-args: |
            HTTP_URL=http://localhost:3001
            WS_URL=ws://localhost:8080
          push: true
          tags: devanshbhavsar/drawify-frontend:${{ github.sha }}

      - name: running docker container on vm
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker kill frontend
            sudo docker rm frontend
            sudo docker pull devanshbhavsar/drawify-frontend:${{ github.sha }}
            sudo docker run --name frontend -d -p 3000:3000 devanshbhavsar/drawify-frontend:${{ github.sha }}
