name: Websocket Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/Dockerfile.http-backend
          push: true
          tags: devanshbhavsar/drawify-websocket-backend:${{ github.sha }}

      - name: running docker container on vm
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker kill ws-backend
            sudo docker rm ws-backend
            sudo docker pull devanshbhavsar/drawify-websocket-backend:${{ github.sha }}
            sudo docker run --name ws-backend -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} devanshbhavsar/drawify-websocket-backend:${{ github.sha }}
